language: node_js
services:
  - mongodb
  - redis-server
node_js:
  - "11.15.0"
before_script:
  - npm install -g grunt-cli
  - redis-cli config set notify-keyspace-events Ex
script:
  - commitlint-travis
